[app]
default_role_name = "默认角色"
default_role_desc = "默认角色，无法删除。"
public_routes = [ "/auth/token", "/auth/verification", "/auth/pub-key", "/static",]

[auth]
rsa_public_key_path = "static/rsa_pub_key.pem"
rsa_private_key_path = "data/rsa_pri_key.pem"
jwt_secret = ""
admin_email = "admin@qiuying.tech"
admin_password = "123456"
access_token_key = "x-access-token"
access_expire = 3600
refresh_expire = 86400

[email]
sender_name = "Qiuying RPA<noreply>"
sender_address = "noreply@qiuying.tech"
sender_password = ""
host = "smtp.exmail.qq.com"
port = 465
